#pragma once
#include <iostream>
#include <cstdlib>
#include <sstream>
#include <cstring>
#include <fstream>
#include <string>
#include <algorithm>
#include <windows.h>
#include <Winbase.h>
#include <Shldisp.h>
#include <vector>
#include <io.h>
#include <cmath>
#include <Windowsx.h>
#include <cstdio>
#include <gdiplus.h>
#include <wingdi.h>
#include <objidl.h>
#include <thread>